version: '2'
services:
    # web server & tools
    php:
        build: ./docker/php/
        environment:
            TIMEZONE: Asia/Novosibirsk
        volumes:
            - ./app:/var/www/app
            - ./docker/php/host.conf:/etc/apache2/sites-enabled/000-default.conf
        working_dir: /var/www/app
        ports:
            - ${HTTP_DEV_SERVER_PORT}:80
        links:
            - rabbitmq
    # Databases
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - ${MYSQL_DEV_SERVER_PORT}:3306
        environment:
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
              MYSQL_DATABASE: ${MYSQL_DATABASE}
              MYSQL_USER: ${MYSQL_USER}
              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql
    # Tools
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: "mysql"
        depends_on:
            - mysql
        ports:
            - ${MYADMIN_DEV_SERVER_PORT}:80
    # RabbitMQ Queue
    rabbitmq:
        image: rabbitmq:3.6.1-management
        environment:
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        ports:
            - ${RABBITMQ_MANAGEMENT_PORT}:15672
            - ${RABBITMQ_EXCHANGE_PORT}:5672